---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "greeter.fullname" . }}-app-configmap
data:
  DATABASE_URL: {{ .Values.app.databaseUrl | default "" | quote }}
  ENV: {{ .Values.app.env | quote }}
  HOST: {{ .Values.app.host | default "0.0.0.0" | quote }}
  LOG_LEVEL: {{ .Values.app.logLevel | default "info" | lower | quote }}
  PORT: {{ .Values.app.port | default 8085 | quote }}
  TIMEOUT_SECONDS: {{ .Values.app.timeout_seconds | default 30 | quote }}
  WORKERS: {{ .Values.app.workers | default 1 | quote }}