apiVersion: v1
kind: Service
metadata:
  name: {{ include "greeter.fullname" . }}
  labels:
    {{- include "greeter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port | default 8085 }}
      nodePort: {{ .Values.service.nodePort | default 30007 }}
      protocol: TCP
  selector:
    {{- include "greeter.selectorLabels" . | nindent 4 }}