app:
  logLevel: info
  env: some-environment
  host: 0.0.0.0
  port: 8085

image:
  repository: ghcr.io/amentumstudio/chahanchart-greeter
  tag: 0.1.0
  pullPolicy: IfNotPresent

ingress:
  enabled: false

probes:
  initialDelaySeconds: 20

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  port: 8085
