name: CI - Build and Test

on:
  push:
    # Publish semver tags as releases.
    tags: ["v*.*.*"]

env: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      ## SETUP
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set RELEASE_TAG from tag
        run: |
          set -x
          RELEASE_TAG=${GITHUB_REF:-none}
          # uncomment to test if it works correctly
          # RELEASE_TAG=refs/tags/v1.2.3
          RELEASE_TAG=${RELEASE_TAG#refs/*/}
          RELEASE_TAG=${RELEASE_TAG#v*}
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
          # exit 1;
        #run: set -x; export GITHUB_REF='refs/tags/v1.2.3'; echo "RELEASE_TAG=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV; exit 1

      - uses: extractions/setup-just@v3
        with:
          just-version: "1.40.0"

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.10.0

      - name: Get Git commit timestamps
        run: |
          set -x
          echo "GIT_TIMESTAMP=$(git log --max-count=1 --pretty=format:%ct || echo 0)" >> $GITHUB_ENV

      ## TEST
      - name: Build test containers
        uses: docker/bake-action@v6
        env:
          RELEASE_TAG: ${{ env.RELEASE_TAG }}-test
          SOURCE_DATE_EPOCH: ${{ env.GIT_TIMESTAMP }}
        with:
          push: false
          load: true
          source: .
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
          targets: dev

      - name: CI tests
        env:
          tag: ${{ env.RELEASE_TAG }}
          tag-test: ${{ env.RELEASE_TAG }}-test
        run: |
          export RELEASE_VERSION='${{ env.tag }}'
          just ci-test '${{ env.tag-test }}'
          just ci-test-cleanup '${{ env.tag-test }}'

      ## RELEASE
      - name: Build & Push prod containers
        uses: docker/bake-action@v6
        env:
          RELEASE_TAG: ${{ env.RELEASE_TAG }}
          SOURCE_DATE_EPOCH: ${{ env.GIT_TIMESTAMP }}
        with:
          push: true
          load: false
          source: .
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
          targets: prod
